packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  msgpackr-extract: true
  msw: true
  prisma: true

nodeLinker: hoisted
packageImportMethod: copy
